version: '2'
services:
 apptest:
  build:
   context: ./docker/
   dockerfile: ./app.docker
  command: python3 /app/expsys.py -d
  volumes:
   - ./app/:/app/
   - $HOME/.Xauthority:/root/.Xauthority
  environment:
         DISPLAY: $DISPLAY
  network_mode: "host"

 appprod:
  build:
   context: ./docker/
   dockerfile: ./app.docker
  command: python3 /app/expsys.py 
  volumes:
   - ./app/:/app/
